# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 336)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.COMList = QtWidgets.QComboBox(self.centralwidget)
        self.COMList.setGeometry(QtCore.QRect(10, 10, 73, 22))
        self.COMList.setObjectName("COMList")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(200, 10, 93, 28))
        self.connectButton.setObjectName("connectButton")
        self.heightLCD = QtWidgets.QLCDNumber(self.centralwidget)
        self.heightLCD.setGeometry(QtCore.QRect(10, 60, 101, 51))
        self.heightLCD.setObjectName("heightLCD")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(100, 10, 93, 28))
        self.refreshButton.setObjectName("refreshButton")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(20, 140, 51, 51))
        self.button1.setObjectName("button1")
        self.button2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(90, 140, 51, 51))
        self.button2.setObjectName("button2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 140, 51, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 140, 51, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.upButton = QtWidgets.QPushButton(self.centralwidget)
        self.upButton.setGeometry(QtCore.QRect(160, 60, 51, 51))
        self.upButton.setObjectName("upButton")
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(230, 60, 51, 51))
        self.downButton.setObjectName("downButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 26))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_Position_1 = QtWidgets.QAction(MainWindow)
        self.actionSet_Position_1.setObjectName("actionSet_Position_1")
        self.actionSet_Position_2 = QtWidgets.QAction(MainWindow)
        self.actionSet_Position_2.setObjectName("actionSet_Position_2")
        self.actionSet_Position_3 = QtWidgets.QAction(MainWindow)
        self.actionSet_Position_3.setObjectName("actionSet_Position_3")
        self.actionSet_Position_4 = QtWidgets.QAction(MainWindow)
        self.actionSet_Position_4.setObjectName("actionSet_Position_4")
        self.menuSettings.addAction(self.actionSet_Position_1)
        self.menuSettings.addAction(self.actionSet_Position_2)
        self.menuSettings.addAction(self.actionSet_Position_3)
        self.menuSettings.addAction(self.actionSet_Position_4)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.pushButton.setText(_translate("MainWindow", "3"))
        self.pushButton_2.setText(_translate("MainWindow", "4"))
        self.upButton.setText(_translate("MainWindow", "↑"))
        self.downButton.setText(_translate("MainWindow", "↓"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionSet_Position_1.setText(_translate("MainWindow", "Set Position 1"))
        self.actionSet_Position_2.setText(_translate("MainWindow", "Set Position 2"))
        self.actionSet_Position_3.setText(_translate("MainWindow", "Set Position 3"))
        self.actionSet_Position_4.setText(_translate("MainWindow", "Set Position 4"))
